[workspace]
name = "apf_demo"
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[dependencies]
python = "3.11.*"
numpy = "*"
matplotlib = "*"

[tasks]
start = "python main.py"